GET http://localhost:3000/fruits

###
GET http://localhost:3000/fruits/5

###
POST http://localhost:3000/fruits
content-type: application/json

{
  "name": "mango",
  "color": "orange",
  "family": "stonefruit",
  "image_url": "https://images.albertsons-media.com/is/image/ABS/184150300?$ecom-pdp-desktop$&defaultImage=Not_Available&defaultImage=Not_Available"
}

###
PATCH http://localhost:3000/fruits/5
content-type: application/json

{
  "name": "pineapple"
}

###
DELETE http://localhost:3000/fruits/6